FORMAT: 1A

# Todo

Todo is a simple API allowing users they can keep track of your tasks need to be done.

# Group Todos

Resources related to todos in the API.

## Todo Collection [/api/v1/all]

A Todo object has the following attributes.

- Item

### List All Todos [GET]

+ Response 200 (application/json)
    + Headers
        content-type: text/plain; charset=utf-8
    + Body
        {
            "Todos": [
                "Wake up",
                "Prepare breakfast",
                "Get dressed",
                "Go to work",
                "My New Task"
              ],
              "Message": ""
        }

## Todo [/api/v1/add]

Resources related to single Todo Model.

### Create a new todo [POST]

You can create todo using this action. It takes a JSON object containing task_description.

+ Item (string)

+ Request (application/json)
    {
        "Item": "My New Task"
    }
+ Response 200 (application/json)
    + Headers
        content-type: text/plain; charset=utf-8
    + Body {
         {
            "Todos": [],
            "Message": "OK"
        }
    }
