
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todon-prod
  name: webserver-prod-deployment
  labels:
    app: webserver-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver-prod
  template:
    metadata:
      labels:
        app: webserver-prod
    spec:
      initContainers:
      - name: wait-for-memcacheserver
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://memcacheserver-prod-clusterip/health -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the memcacheserver...'; done"]
      containers:
      - name: webserver-prod
        image: devhsmtek/webserver_prod:latest
        imagePullPolicy: "Always"
        envFrom:
          - configMapRef:
              name: webserver-prod-config
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5