apiVersion: v1
kind: Service
metadata:
  namespace: todon-prod
  name: memcacheserver-prod-clusterip
spec:
  type: ClusterIP
  selector:
    app: memcacheserver-prod
  ports:
    - protocol: TCP
      name: grpc
      port: 33800
      targetPort: 33800
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80