
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-test-deployment
  labels:
    app: webserver-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-test
  template:
    metadata:
      labels:
        app: webserver-test
    spec:
      initContainers:
      - name: wait-for-memcacheserver
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args: ["while [ $(curl -sw '%{http_code}' http://memcacheserver-clusterip/health -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the memcacheserver...'; done"]
      containers:
      - name: memcacheserver
        image: devhsmtek/webserver:latest
        imagePullPolicy: "Always"
        envFrom:
          - configMapRef:
              name: webserver-config
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5