apiVersion: v1
kind: Service
metadata:
  name: webserver-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - name: httplistener
      port: 80
      targetPort: 80
      nodePort: 30082