# Start from the latest golang base image
FROM golang:latest as builder

LABEL maintainer="Hüsamettin ARABACI <husamettin.arabaci@hsmteknoloji.com>"

COPY . /
WORKDIR /Services/FE_Services/webserver
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o webserver .


######## Start a new stage from scratch #######
FROM alpine:latest  

RUN apk --no-cache add ca-certificates
RUN apk add --no-cache tzdata
ENV TZ=Europe/Istanbul
WORKDIR /root/

ENV CONTAINER_TYPE=webserver

COPY --from=builder /Services/FE_Services/webserver/webserver .
COPY --from=builder /Services/FE_Services/webserver/views/ ./views

CMD ["./webserver"]