apiVersion: v1
kind: Service
metadata:
  namespace: todon-prod
  name: memcacheserver-prod-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: memcacheserver-prod
  ports:
    - name: grpclistener
      port: 33800
      targetPort: 33800
      nodePort: 30087