apiVersion: v1
kind: Service
metadata:
  namespace: todon-prod
  name: webserver-prod-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: webserver-prod
  ports:
    - name: httplistener
      port: 80
      targetPort: 80
      nodePort: 30088