name: ToDoN CI/CD

on:
  push:
    branches: [ main ]

jobs:
  web-test-api-cdc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /Configs/DockerFiles
    steps:
    - name: API CDC Test
      run: docker build -f Dockerfile_webserver_apicdctest -t dredd . && docker image rm dredd